config/routes.rb
Feedback::Application.routes.draw do

  get "home/index"

  resources :users, :only => [] do
    get :new_password, :on => :member
    put :create_password, :on => :member
    put :update_feedback, :on => :member
    get :change_password, :on => :member
    put :update_password, :on => :member
    put :update_reset_password, :on => :member
    get :reset_password, :on => :member
    get :give_feedback, :on => :collection
    get :received_feedback, :on => :collection
    get :received_feedback_search, :on => :collection
    get :forgot_password, :on => :collection
    post :forgot_password_reset, :on => :collection
  end

  namespace :admin do
    resources :admins, :only => [:index] do
      get :add_user, :on => :collection
      post :create_user, :on => :collection
      get :assigned_feedback_list, :on => :collection
      get :assigned_feedback_search, :on => :collection
      get :reset_password, :on => :member
      put :update_password, :on => :member
    end
    resources :users, :only => [:index] do
      get :assign_user, :on => :collection
      get :get_from_user_list, :on => :collection
      get :get_to_user_list, :on => :collection
      get :create_assign_user, :on => :collection
      get :given_feedback_search, :on => :collection
      get :received_feedback_search, :on => :collection
      get :to_feedback, :on => :member
      get :from_feedback, :on => :member
      delete :delete_user, :on => :member
      get :reset_password, :on => :member
    end
  end
  resources :user_sessions, :only => [:new, :create, :destroy]
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

  root :to => 'home#index'

end

app/views/shared/_footer.html.erb
<div style="margin-top: 20px;"><div class="container" id="footer" style="border-top: 1px solid #000;">
  <div class="row" style="padding-top: 20px;">
    <div class="span8">
      <h5>© 2012 Weboniselab All Rights Reserved</h5>
    </div>
    <div class="pull-right">
      <h5>Powered by
        <a href="http://www.weboniselab.com/" class="weboniseLogo" style="color:#84c225;" target="_blank"><img src="/assets/webonise_logo.png"  alt="">weboniselab</a>
      </h5>
    </div>
    <%#= debug(params) if Rails.env.development? %>
  </div>
</div>
</div>

app/views/shared/_top_link.html.erb
<% if current_admin %>
    <ul class="nav">
      <li ><%= link_to "Users", admin_users_path %></li>
    </ul>
    <ul class="nav">
      <li ><%= link_to "Assigned List", assigned_feedback_list_admin_admins_path %></li>
    </ul>
    <ul class="nav">
      <li ><%= link_to "Add User", add_user_admin_admins_path %></li>
    </ul>
    <ul class="nav pull-right">
      <li ><%= link_to "logout", logout_path %></li>
    </ul>
    <ul class="nav pull-right">
      <li ><%= link_to "Change Password",  reset_password_admin_admin_path(logged_in_user) %></li>
    </ul>
<% end %>
<% if current_user %>
    <ul class="nav">
      <li ><%= link_to "Give Feedback",  give_feedback_users_path %></li>
    </ul>
    <ul class="nav">
      <li ><%= link_to "Received Feedback",  received_feedback_users_path %></li>
    </ul>
    <ul class="nav pull-right">
      <li ><%= link_to "logout", logout_path %></li>
    </ul>
    <ul class="nav pull-right">
      <li ><%= link_to "Change Password",   change_password_user_path(logged_in_user) %></li>
    </ul>
    <ul class="nav pull-right">
      <li > <%=link_to "welcome #{logged_in_user.name} ",nil , :remote => true %></li>
    </ul>
<% end %>
<% if !logged_in_user %>
    <ul class="nav pull-right">
      <li ><%= link_to "Login", login_path %></li>
    </ul>
<% end %>