config/routes.rb
Feedback::Application.routes.draw do

  get "home/index"

  resources :users, :only => [] do
    get :new_password, :on => :member
    put :create_password, :on => :member
    put :update_feedback, :on => :member
    get :change_password, :on => :member
    put :update_password, :on => :member
    put :update_reset_password, :on => :member
    get :reset_password, :on => :member
    get :give_feedback, :on => :collection
    get :received_feedback, :on => :collection
    get :received_feedback_search, :on => :collection
    get :forgot_password, :on => :collection
    post :forgot_password_reset, :on => :collection
  end

  namespace :admin do
    resources :admins, :only => [:index] do
      get :add_user, :on => :collection
      post :create_user, :on => :collection
      get :assigned_feedback_list, :on => :collection
      get :assigned_feedback_search, :on => :collection
      get :reset_password, :on => :member
      put :update_password, :on => :member
    end
    resources :users, :only => [:index] do
      get :assign_user, :on => :collection
      get :get_from_user_list, :on => :collection
      get :get_to_user_list, :on => :collection
      get :create_assign_user, :on => :collection
      get :given_feedback_search, :on => :collection
      get :received_feedback_search, :on => :collection
      get :to_feedback, :on => :member
      get :from_feedback, :on => :member
      delete :delete_user, :on => :member
      get :reset_password, :on => :member
    end
  end
  resources :user_sessions, :only => [:new, :create, :destroy]
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

  root :to => 'home#index'

end

app/views/admin/admins/_assigned_feedback_list.html.erb
<table class="table" style="background: #e0efcd;">
  <colgroup>
    <col class="span3">
    <col class="span3">
  </colgroup>
  <caption>
    <h2>Assigned Feedback List</h2>
  </caption>
  <thead>
  <tr class="th_bg">
    <th style="border-right: 1px solid;"><div style="float: left;" ><%= link_to "<<",nil, :class => "btn arrow_btn", :style => "padding-bottom: -5px;", :remote => true, :id => "previous-assigned-feedback", :date => end_date.prev_month.next_week.strftime("%d-%b-%Y")%></div><div align="center"><h3><%= end_date.strftime("%B-%Y")  %></h3></div></th>
    <th><div style="float: right;"><%= link_to ">>",nil, :class => "btn arrow_btn", :style => "padding-bottom: -5px;", :remote => true, :id => "next-assigned-feedback", :date => end_date.advance(:months => 1).beginning_of_month.next_week.strftime("%d-%b-%Y")%></div><div align="center"><h3><%= end_date.next_month.strftime("%B-%Y")%></h3></div></th>
  </tr>
  <% for i in 1..5 %>
      <%
         end_date = end_date.end_of_week - 2.days
         begin_date = begin_date.beginning_of_week
         next_month_end_date = next_month_end_date.end_of_week - 2.days
         next_month_begin_date = next_month_begin_date.beginning_of_week
         first_month_feedbacks = feedbacks.select{|f|f.created_at>= begin_date.beginning_of_day and f.created_at <= end_date.end_of_day}
         second_month_feedbacks = feedbacks.select{|f|f.created_at>= next_month_begin_date.beginning_of_day and f.created_at <= next_month_end_date.end_of_day}
      %>
      <tr>
        <td  style="border-right: 1px solid; border-top: none; width: 50%"><%= render :partial => "week_assigned_feedback_list", :locals => {:users => users, :feedbacks => first_month_feedbacks,  :begin_date => begin_date, :end_date => end_date } %></td>
        <td style="border-top: none; width: 50%"><%= render :partial => "week_assigned_feedback_list", :locals => {:users => users, :feedbacks => second_month_feedbacks, :begin_date => next_month_begin_date, :end_date => next_month_end_date } %></td>
      </tr>
      <% temp = end_date.next_week(:monday)  %>
      <% begin_date = temp; end_date = end_date.next_week(:friday)  %>
      <% temp = next_month_end_date.next_week(:monday)  %>
      <% next_month_begin_date = temp; next_month_end_date = next_month_end_date.next_week(:friday)  %>
  <% end %>
  </table>
<%= link_to "Back", admin_users_path, :class => "btn" %>

app/views/admin/admins/_week_assigned_feedback_list.html.erb
<% given_user = feedbacks.to_a.uniq{|u| u.from_id} %>
<table class="table main-table" style="background-color: #fff;">
  <colgroup>
    <col class="span2">
    <col class="span3">
  </colgroup>
  <caption>
    <h4><%= begin_date.nil? ? "" : "( #{begin_date.strftime("%d-%b-%Y")} to #{end_date.strftime("%d-%b-%Y")}) #{week_number(begin_date)} " %></h4>
  </caption>
  <thead style="border-bottom: 1px solid #84c225">
  <tr>
    <th>Contributor</th>
    <th>Recipients</th>
  </tr>
  </thead>
  <% if given_user.length != 0 %>
      <% given_user.each do |user| %>
          <tr>
            <td><%= user_name(users,user.from_id) %></td>
            <% received_users = feedbacks.to_a.select{|u| u.from_id == user.from_id} %>
            <% received_users = received_users.to_a.uniq{|u| u.to_id} %>
            <td>
              <% received_users.each do |received_user| %>
                  <%= user_name(users,received_user.to_id) %>
              <% end %>
            </td>
          </tr>
      <% end %>
      <% if given_user.count < 3 %>
          <% for i in 1..(3 - given_user.count)  %>
              <tr>
                <td>&nbsp;</td>
                <td></td>
              </tr>
          <% end %>
      <% end %>
  <% else%>
      <tr>
        <td>&nbsp;</td>
        <td></td>
      </tr>
      <tr>
        <td>&nbsp;</td>
        <td></td>
      </tr>
      <tr>
        <td>&nbsp;</td>
        <td></td>
      </tr>
  <% end %>
</table>

app/views/admin/admins/add_user.html.erb
<% if @user.errors.any? %>
    <div class="alert alert-error" align="center">
      <a class="close" data-dismiss="alert"> × </a>
      <% @user.errors.full_messages.each do |msg| %>
          <p><%= msg %></p>
      <% end %>
    </div>
<%end%>
<div class="row">
  <div class="span5 offset3 login_container" >
    <%= form_tag create_user_admin_admins_path, :class => "form-horizontal", :method => "POST" do %>
        <legend>Create User</legend>
        <div class="control-group">
          <label class="control-label">
            Name
          </label>
          <div class="controls">
            <%= text_field_tag :name, params[:name], :required => true %>
          </div>
        </div>
        <div class="control-group">
          <label class="control-label">
            Email
          </label>
          <div class="controls">
            <%= email_field_tag :email, params[:email], :required => true %>
          </div>
        </div>
        <div class="control-group">
          <div class="controls">
            <%= submit_tag "Create User", :class => "btn btn-inverse" %>
            <%= link_to "Cancel", admin_users_path, :class => "btn" %>
          </div>
        </div>
    <% end %>
  </div>
</div>
<div class="row">
  <div class="span10 offset2 webonise_logo">
    <img src="/assets/weboniselab.png" >
  </div>
</div>

app/views/admin/admins/assigned_feedback_list.html.erb
<!--<div class="pull-right">-->
  <!--<input type="text" data-behaviour='datepicker' id="datepicker" >-->
  <!--<%#= link_to "search", nil, :class => "btn btn-info", :style => "margin-top:-9px; margin-left:-4px;", :remote => true, :id => "assigned-feedback-search" %>-->
<!--</div>-->
<div id="assigned-feedback-list">
  <%= render :partial => "assigned_feedback_list", :locals => {:users => @users, :feedbacks => @feedbacks, :begin_date => @begin_date, :end_date =>  @begin_date.end_of_week,:next_month_begin_date => @begin_date.next_week.next_month.beginning_of_month.beginning_of_week , :next_month_end_date => @begin_date.next_week.next_month.beginning_of_month.end_of_week} %>
</div>

app/views/admin/admins/assigned_feedback_search.html.erb
<div class="pull-right">
  <input type="text" data-behaviour='datepicker' id="datepicker" >
  <%= link_to "search", nil, :class => "btn btn-info", :style => "margin-top:-9px; margin-left:-4px;", :remote => true, :id => "assigned-feedback-search" %>
</div>
<div id="assigned-feedback-list">
  <%= render :partial => "assigned_feedback_list", :locals => {:users => @users, :recipients => @recipients, :feedbacks => @feedbacks, :begin_date => @begin_date.strftime("%d-%b-%Y"), :end_date => @end_date.strftime("%d-%b-%Y")} %>
</div>

app/views/admin/admins/assigned_feedback_search.js.erb
$("#assigned-feedback-list").html("<%= escape_javascript(render :partial => "assigned_feedback_list", :locals => {:users => @users, :feedbacks => @feedbacks, :begin_date => @begin_date, :end_date =>  @begin_date.end_of_week,:next_month_begin_date => @begin_date.next_week.next_month.beginning_of_month.beginning_of_week , :next_month_end_date => @begin_date.next_week.next_month.beginning_of_month.end_of_week}) %>");
$('.main-table').oneSimpleTablePagination({rowsPerPage:3});

app/views/admin/admins/from_feedback.html.erb
<table class="table table-bordered">
  <colgroup>
    <col class="span2">
    <col class="span3">
    <col class="span3">
    <col class="span3">
  </colgroup>
  <caption>
    <h2>Feedback List</h2>
  </caption>
  <thead>
  <tr>
    <th>Name</th>
    <th>Assigned Date</th>
    <th>Date</th>
    <th>Feedback</th>
  </tr>
  </thead>
  <% @feedbacks.each do |feedback| %>
      <tr>
        <td><%= user_name(feedback.to_id) %></td>
        <td><%= date(feedback.created_at) %></td>
        <td><%= date(feedback.updated_at) if !feedback.feedback.to_s.empty? %></td>
        <td><%= feedback.feedback if !feedback.feedback.to_s.empty? %></td>
      </tr>
  <% end %>
</table>
<%= link_to "Back", user_list_admin_admins_path, :class => "btn" %>

app/views/admin/admins/index.html.erb
<div>
  <h1 align="center" style="color:#429FCC">Welcome Administrator</h1>
  <%= image_tag("webonise2.png", :style => "margin: auto; display: block;") %>
</div>

app/views/admin/admins/reset_password.html.erb
<% if @admin.errors.any? %>
    <div class="alert alert-error" align="center">
      <a class="close" data-dismiss="alert"> × </a>
      <% @admin.errors.full_messages.each do |msg| %>
          <p><%= msg %></p>
      <% end %>
    </div>
<%end%>
<div class="row">
  <div class="span5 offset3 login_container" >
    <%= form_for @admin, :url => { :action => "update_password"}, :html => {:class => "form-horizontal"}, :method => "PUT" do |f|%>
        <legend>Change Password</legend>
        <div class="control-group">
          <label class="control-label" style="font-size: 15px;">
            New Password
          </label>
          <div class="controls">
            <%= f.password_field :password, :required => true %>
          </div>
        </div>
        <div class="control-group">
          <label class="control-label" style="font-size: 15px;">
            Confirm Password
          </label>
          <div class="controls">
            <%= f.password_field :password_confirmation, :required => true %>
          </div>
        </div>
        <div class="control-group">
          <div class="controls">
            <%= f.submit "Reset Password", :class => "btn btn-inverse" %>
            <%= link_to "Cancel", admin_users_path, :class => "btn" %>
          </div>
        </div>
    <% end %>
  </div>
</div>
<div class="row">
  <div class="span10 offset2 webonise_logo">
    <img src="/assets/weboniselab.png" >
  </div>
</div>

app/views/admin/admins/to_feedback.html.erb
<table class="table table-bordered">
  <colgroup>
    <col class="span2">
    <col class="span3">
    <col class="span3">
    <col class="span3">
  </colgroup>
  <caption>
    <h2>Feedback List</h2>
  </caption>
  <thead>
  <tr>
    <th>Name</th>
    <th>Assigned Date</th>
    <th>Date</th>
    <th>Feedback</th>
  </tr>
  </thead>
  <% @feedbacks.each do |feedback| %>
      <tr>
        <td><%= user_name(feedback.from_id) %></td>
        <td><%= date(feedback.created_at) %></td>
        <td><%= date(feedback.updated_at) if !feedback.feedback.to_s.empty? %></td>
        <td><%= feedback.feedback if !feedback.feedback.to_s.empty? %></td>
      </tr>
  <% end %>
</table>
<%= link_to "Back", user_list_admin_admins_path, :class => "btn" %>

app/views/admin/admins/user_list.html.erb
<table class="table table-bordered">
  <colgroup>
    <col class="span2">
    <col class="span3">
    <col class="span3">
    <col class="span3">
  </colgroup>
  <caption>
    <h2>User List</h2>
  </caption>
  <thead>
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Email</th>
    <th>Feedback</th>
  </tr>
  </thead>
  <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td>
          <%= link_to "Taken",to_feedback_admin_admin_path(user), :class => "btn btn-success" %>
          <%= link_to "Given",from_feedback_admin_admin_path(user), :class => "btn btn-success" %>
        </td>
      </tr>
  <% end %>
</table>