config/routes.rb
Feedback::Application.routes.draw do

  get "home/index"

  resources :users, :only => [] do
    get :new_password, :on => :member
    put :create_password, :on => :member
    put :update_feedback, :on => :member
    get :change_password, :on => :member
    put :update_password, :on => :member
    put :update_reset_password, :on => :member
    get :reset_password, :on => :member
    get :give_feedback, :on => :collection
    get :received_feedback, :on => :collection
    get :received_feedback_search, :on => :collection
    get :forgot_password, :on => :collection
    post :forgot_password_reset, :on => :collection
  end

  namespace :admin do
    resources :admins, :only => [:index] do
      get :add_user, :on => :collection
      post :create_user, :on => :collection
      get :assigned_feedback_list, :on => :collection
      get :assigned_feedback_search, :on => :collection
      get :reset_password, :on => :member
      put :update_password, :on => :member
    end
    resources :users, :only => [:index] do
      get :assign_user, :on => :collection
      get :get_from_user_list, :on => :collection
      get :get_to_user_list, :on => :collection
      get :create_assign_user, :on => :collection
      get :given_feedback_search, :on => :collection
      get :received_feedback_search, :on => :collection
      get :to_feedback, :on => :member
      get :from_feedback, :on => :member
      delete :delete_user, :on => :member
      get :reset_password, :on => :member
    end
  end
  resources :user_sessions, :only => [:new, :create, :destroy]
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

  root :to => 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :role, :password_confirmation
  acts_as_authentic

  has_many :from, :class_name => UserFeedback, :foreign_key => :from_id, :dependent => :destroy
  has_many :to, :class_name => UserFeedback, :foreign_key => :to_id, :dependent => :destroy

  validates :name, :email, :password, :presence => true;
  validates :password, :length => {:minimum => 4}

  def self.create_user(email, name)
    password = SecureRandom.base64(15).tr('+/=', '').strip.delete("\n")
    self.create(:email => email, :name => name, :password => password, :password_confirmation => password)
  end

  #def self.user_mail
  #  @users = self.where(:role => "user")
  #  @users.each do |user|
  #    UserMailer.demo(user).deliver
  #  end
  #end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_filter :admin_should_be_login
  before_filter :find_user, :only => [:to_feedback, :from_feedback, :given_feedback_search, :received_feedback_search, :delete_user, :reset_password]
  before_filter :find_week, :only => [:given_feedback_search, :received_feedback_search]
  before_filter :find_current_week, :only => [:to_feedback, :from_feedback, :assigned_feedback]
  before_filter :all_user
  #before_filter :assigned_user_feedback, :only => [:assigned_feedback, :assigned_feedback_search]
  before_filter :given_user_feedback, :only => [:from_feedback, :given_feedback_search]
  before_filter :received_user_feedback, :only => [:to_feedback, :received_feedback_search]

  def index
    @users = @users.to_a.paginate(:page => params[:page], :per_page => 10)
  end

  def assign_user
  end

  def get_from_user_list
    @feedback = UserFeedback.where(:created_at => (Time.now.in_time_zone('UTC').beginning_of_day)..(Time.now.in_time_zone('UTC').end_of_day))
    feedback = @feedback.collect{|f| f.from_id}.zip(params[:from_user] ? params[:from_user] : []).flatten.compact.collect{|s| s.to_i}.uniq
    @users = User.where("id not in(?) and role = 'user' and name LIKE '%#{params[:name_startsWith]}%'", feedback.present? ? feedback : '' )
    render :json => @users
  end

  def get_to_user_list
    @users = User.where("id not in(?) and role = 'user' and name LIKE '%#{params[:name_startsWith]}%'", params[:from_user])
    render :json => @users
  end

  def create_assign_user
    if UserFeedback.assign_feedback(params)
      render :json => {:success => true}
    else
      render :json => {:success => false}
    end
  end

  def to_feedback
  end

  def from_feedback
  end

  def delete_user
    @user.to.delete_all
    @user.from.delete_all
    @user.delete
    redirect_to admin_users_path
  end

  def reset_password
    UserMailer.password_reset_mail(@user).deliver
    redirect_to admin_users_path
  end

  def given_feedback_search

    respond_to do |format|
      format.js
      format.html
    end
  end

  def received_feedback_search
    respond_to do |format|
      format.js
      format.html
    end
  end


  protected
  #
  #def assigned_user_feedback
  #  @feedbacks = @user.from.where(:created_at => @begin_date..@end_date)
  #  @feedbacks = @feedbacks.to_a.uniq{|feedback| feedback.to_id}
  #  @feedbacks = @feedbacks.paginate(:page => params[:page], :per_page => 10)
  #end

  def given_user_feedback
    #@feedbacks =  @user.from.where("created_at BETWEEN '#{@begin_date}' AND '#{@end_date}' AND feedback is NOT NULL").paginate(:page => params[:page], :per_page => 10).order('created_at'}' ")
    @feedbacks =  @user.from.where("created_at BETWEEN '#{@begin_date}' AND '#{@end_date}' ")
  end

  def received_user_feedback
    @feedbacks =  @user.to.where("created_at BETWEEN '#{@begin_date}' AND '#{@end_date}' AND feedback is NOT NULL").paginate(:page => params[:page], :per_page => 10).order('updated_at desc')
  end

  def find_user
    @user = User.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :user_should_be_login, :except => [:new_password, :create_password, :forgot_password, :forgot_password_reset, :reset_password, :update_reset_password]
  before_filter :find_user_by_perishable_token, :only => [:new_password, :create_password, :reset_password, :update_reset_password]
  before_filter :find_current_week, :only => [:given_feedback, :received_feedback]
  before_filter :find_week, :only => [:given_feedback_search, :received_feedback_search]
  before_filter :all_user, :only => [:give_feedback, :received_feedback, :received_feedback_search]
  before_filter :received_user_feedback, :only => [:received_feedback, :received_feedback_search]

  #def index
  #end
  def new_password
    if !@user
      redirect_to new_user_session_path
    end
  end
  def change_password
    @user = logged_in_user
  end
  def update_password
    @user = logged_in_user
    if @user.update_attributes(:password => params[:user][:password], :password_confirmation => params[:user][:password_confirmation])
      redirect_to home_index_path,:notice => "password reset successfully!!!!"
    else
      render :change_password
    end
  end

  def create_password
    if @user.update_attributes(params[:user])
      redirect_to  home_index_path, :notice  => "password created successfully!!!!"
    else
      render :new_password
    end
  end

  def forgot_password
  end

  def forgot_password_reset
    if @user = User.find_by_email(params[:email])
      UserMailer.password_reset_mail(@user).deliver
      redirect_to home_index_path, :notice => "You will receive an email with instructions about how to reset your password shortly."
    else
      redirect_to forgot_password_users_path, :flash => { :error => "Enter a valid email address" }
    end
  end

  def reset_password
    if @user.nil?
      redirect_to home_index_path
    end
  end
  def update_reset_password
    if @user.update_attributes(params[:user])
      #redirect_to logout_path(@user)
      @user_session = UserSession.find
      @user_session.destroy
      redirect_to home_index_path, :notice  => "password reset successfully"
    else
      render :reset_password
    end
  end

  def update_feedback
    feedback = UserFeedback.find(params[:id])
    if feedback.update_attributes(:feedback => params[:feedback])
      respond_to do |format|
        format.js {render :layout => false}
      end
    else
      redirect_to give_feedback_users_path
    end
  end

  def give_feedback
    feedbacks = logged_in_user.from.where(:feedback => nil)
    @feedbacks = feedbacks.empty? ? "" : feedbacks.select{|feedback|feedback.created_at >= Time.now.beginning_of_day and feedback.created_at <= Time.now.end_of_day}
  end

  def received_feedback
  end

  def received_feedback_search
    respond_to do |format|
      format.js
      format.html
    end
  end

  protected

  def received_user_feedback
    @feedbacks = logged_in_user.to.where("created_at BETWEEN '#{@begin_date}' AND '#{@end_date}' AND feedback is NOT NULL").paginate(:page => params[:page], :per_page => 10).order('updated_at desc')
  end

  def find_user_by_perishable_token
    @user = User.find_by_perishable_token(params[:id])
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_from_feedback.html.erb
<table class="table" style="background: #e0efcd;">
  <colgroup>
    <col class="span3">
    <col class="span3">
  </colgroup>
  <caption>
    <h2>List of Feedback by <%= user.name %>(Given)</h2>
  </caption>
  <thead>
  <tr class="th_bg">
    <th style="border-right: 1px solid;"><div style="float: left;" ><%= link_to "<<",nil, :class => "btn arrow_btn", :style => "padding-bottom: -5px;", :remote => true, :id => "previous-given", :date => end_date.prev_month.next_week.strftime("%d-%b-%Y"), :user_id => user.id %></div><div align="center"><h3><%= end_date.strftime("%B-%Y")  %></h3></div></th>
    <th><div style="float: right;"><%= link_to ">>",nil, :class => "btn arrow_btn", :style => "padding-bottom: -5px;", :remote => true, :id => "next-given", :date => end_date.advance(:months => 1).beginning_of_month.next_week.strftime("%d-%b-%Y"), :user_id => user.id  %></div><div align="center"><h3><%= end_date.next_month.strftime("%B-%Y")%></h3></div></th>
  </tr>
  <% for i in 1..5 %>
      <%
         end_date = end_date.end_of_week - 2.days
         begin_date = begin_date.beginning_of_week
         next_month_end_date = next_month_end_date.end_of_week - 2.days
         next_month_begin_date = next_month_begin_date.beginning_of_week
         first_month_feedbacks = feedbacks.select{|f|f.created_at>= begin_date.beginning_of_day and f.created_at <= end_date.end_of_day}
         second_month_feedbacks = feedbacks.select{|f|f.created_at>= next_month_begin_date.beginning_of_day and f.created_at <= next_month_end_date.end_of_day}
      %>
      <tr>
        <td  style="border-right: 1px solid; border-top: none; width: 50%"><%= render :partial => "week_from_feedback", :locals => {:users => users, :feedbacks => first_month_feedbacks, :user => user,  :begin_date => begin_date, :end_date => end_date } %></td>
        <td style="border-top: none;width: 50%"><%= render :partial => "week_from_feedback", :locals => {:users => users, :feedbacks => second_month_feedbacks, :user => user,  :begin_date => next_month_begin_date, :end_date => next_month_end_date } %></td>
      </tr>
      <% temp = end_date.next_week(:monday)  %>
      <% begin_date = temp; end_date = end_date.next_week(:friday)  %>
      <% temp = next_month_end_date.next_week(:monday)  %>
      <% next_month_begin_date = temp; next_month_end_date = next_month_end_date.next_week(:friday)  %>
  <% end %>
  </table>
<%= link_to "Back", admin_users_path, :class => "btn" %>

app/views/admin/users/_to_feedback.html.erb
<table class="table" style="background: #e0efcd;">
  <colgroup>
    <col class="span3">
    <col class="span3">
  </colgroup>
  <caption>
    <h2>List of Feedback by <%= user.name %>(Received)</h2>
  </caption>
  <thead>
  <tr class="th_bg">
    <th style="border-right: 1px solid;"><div style="float: left;" ><%= link_to "<<",nil, :class => "btn arrow_btn", :style => "padding-bottom: -5px;", :remote => true, :id => "previous-received", :date => end_date.prev_month.next_week.strftime("%d-%b-%Y"), :user_id => user.id %></div><div align="center"><h3><%= end_date.strftime("%B-%Y")  %></h3></div></th>
    <th><div style="float: right;"><%= link_to ">>",nil, :class => "btn arrow_btn", :style => "padding-bottom: -5px;", :remote => true, :id => "next-received", :date => end_date.advance(:months => 1).beginning_of_month.next_week.strftime("%d-%b-%Y"), :user_id => user.id  %></div><div align="center"><h3><%= end_date.next_month.strftime("%B-%Y")%></h3></div></th>
  </tr>
  <% for i in 1..5 %>
      <%
         end_date = end_date.end_of_week - 2.days
         begin_date = begin_date.beginning_of_week
         next_month_end_date = next_month_end_date.end_of_week - 2.days
         next_month_begin_date = next_month_begin_date.beginning_of_week
         first_month_feedbacks = feedbacks.select{|f|f.created_at>= begin_date.beginning_of_day and f.created_at <= end_date.end_of_day}
         second_month_feedbacks = feedbacks.select{|f|f.created_at>= next_month_begin_date.beginning_of_day and f.created_at <= next_month_end_date.end_of_day}
      %>
      <tr>
        <td  style="border-right: 1px solid; border-top: none;width: 50%"><%= render :partial => "week_to_feedback", :locals => {:users => users, :feedbacks => first_month_feedbacks, :user => user,  :begin_date => begin_date, :end_date => end_date } %></td>
        <td style="border-top: none; width: 50%"><%= render :partial => "week_to_feedback", :locals => {:users => users, :feedbacks => second_month_feedbacks, :user => user,  :begin_date => next_month_begin_date, :end_date => next_month_end_date } %></td>
      </tr>
      <% temp = end_date.next_week(:monday)  %>
      <% begin_date = temp; end_date = end_date.next_week(:friday)  %>
      <% temp = next_month_end_date.next_week(:monday)  %>
      <% next_month_begin_date = temp; next_month_end_date = next_month_end_date.next_week(:friday)  %>
  <% end %>
  </table>
<%= link_to "Back", admin_users_path, :class => "btn" %>

app/views/admin/users/_week_from_feedback.html.erb
<table class="table " style="background-color: #fff;" id="given-feedback">
  <colgroup>
    <col class="span3">
    <col class="span3">
    <col class="span3">
    <col class="span3">
    <col class="span3">
    <col class="span3">
  </colgroup>
  <caption>
    <b><%= begin_date.nil? ? "" : "( #{begin_date.strftime("%d-%b-%Y")} to #{end_date.strftime("%d-%b-%Y")}) #{week_number(begin_date)} " %></b>
  </caption>
  <tr>
    <th>Name</th>
    <th>Mon-<%= begin_date.strftime("%d") %></th>
    <th>Tue-<%= (begin_date + 1.days) .strftime("%d") %></th>
    <th>Wed-<%= (begin_date + 2.days) .strftime("%d") %></th>
    <th>Thu-<%= (begin_date + 3.days) .strftime("%d") %></th>
    <th>Fri-<%= (begin_date + 4.days) .strftime("%d") %></th>
  </tr>
  <% received_user = feedbacks.to_a.uniq{|u| u.to_id} %>
  <%# if received_user.length != 0 %>
      <% received_user.each do |user| %>
          <tr>
            <td><%= user_name(users,user.to_id) %></td>
            <% given_feedbacks =  feedbacks.to_a.select{|f|f.to_id == user.to_id}.sort_by{|feedback| feedback.created_at}%>
            <% if given_feedbacks.count == 5%>
                <% given_feedbacks.each do |feedback|%>
                    <td><%= (feedback.feedback).nil? ? "N/A" : feedback.feedback %></td>
                <% end %>
            <% else %>
                <% for i in 2..given_feedbacks.first.created_at.wday %>
                    <td></td>
                <% end %>
                <% given_feedbacks.each do |feedback|%>
                    <td><%= (feedback.feedback).nil? ? "N/A" : feedback.feedback %></td>
                <% end %>
            <% end %>
          </tr>
      <% end %>
      <% for i in received_user.length..2 %>
          <tr>
            <td>&nbsp;</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
          </tr>
      <% end %>
  <%# else%>
      <!--<tr>-->
        <!--<td>&nbsp;</td>-->
        <!--<td></td>-->
        <!--<td></td>-->
        <!--<td></td>-->
        <!--<td></td>-->
        <!--<td></td>-->
      <!--</tr>-->
      <!--<tr>-->
        <!--<td>&nbsp;</td>-->
        <!--<td></td>-->
        <!--<td></td>-->
        <!--<td></td>-->
        <!--<td></td>-->
        <!--<td></td>-->
      <!--</tr>-->
      <!--<tr>-->
        <!--<td>&nbsp;</td>-->
        <!--<td></td>-->
        <!--<td></td>-->
        <!--<td></td>-->
        <!--<td></td>-->
        <!--<td></td>-->
      <!--</tr>-->
  <%# end %>
</table>
<%#= page_navigation_links feedbacks %>

app/views/admin/users/_week_to_feedback.html.erb
<% given_user = feedbacks.to_a.uniq{|u| u.from_id}#.paginate(:page => params[:page], :per_page => 1) %>
<table class="table main-table" style="background-color: #fff;">
  <colgroup>
    <col class="span2">
    <col class="span3">
    <col class="span3">
    <col class="span3">
    <col class="span3">
    <col class="span3">
  </colgroup>
  <caption>
    <h4><%= begin_date.nil? ? "" : "( #{begin_date.strftime("%d-%b-%Y")} to #{end_date.strftime("%d-%b-%Y")}) #{week_number(begin_date)} " %></h4>
  </caption>
  <thead style="border-bottom: 1px solid #84c225">
  <tr>
    <th>Name</th>
    <th>Mon-<%= begin_date.strftime("%d") %></th>
    <th>Tue-<%= (begin_date + 1.days) .strftime("%d") %></th>
    <th>Wed-<%= (begin_date + 2.days) .strftime("%d") %></th>
    <th>Thu-<%= (begin_date + 3.days) .strftime("%d") %></th>
    <th>Fri-<%= (begin_date + 4.days) .strftime("%d") %></th>
  </tr>
  </thead>
  <% if given_user.length != 0 %>
      <% given_user.each do |user| %>
          <tr>
            <td><%= user_name(users,user.from_id) %></td>
            <% received_feedbacks =  feedbacks.to_a.select{|f|f.from_id == user.from_id}.sort_by{|feedback| feedback.created_at}%>
            <% count = 0 %>
            <% for i in 0..4 %>
                <% feedback = received_feedbacks[count] %>
                <% if (feedback.created_at.wday == i+1 if !feedback.nil?) %>
                    <td><%= feedback.feedback %></td>
                    <% count = count+1 %>
                <% else %>
                    <td></td>
                <% end %>
            <% end %>
          </tr>
      <% end %>
      <% if given_user.count < 3 %>
          <% for i in 1..(3 - given_user.count)  %>
              <tr>
                <td>&nbsp;</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
              </tr>
          <% end %>
      <% end %>
  <% else%>
      <tr>
        <td>&nbsp;</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>&nbsp;</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>&nbsp;</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
  <% end %>
</table>

app/views/admin/users/assign_user.html.erb
<% if get_seconds(Time.now) < 64800 and Time.now.wday >= 1 and Time.now.wday<= 5 %>
    <div id="message" style="float: left; margin-left: 70px; background: #e0efcd;" class="hero-unit">
      <h3>To assign feedback contributor and feedback recipients, please click on "Assign User" button.</h3>
      <input type="button" value="Assign User" class="btn btn-inverse" id = "assign_user1" />
      <%= link_to "Back", admin_users_path, :class => " btn" %>
    </div>
    <input type="button" value="Save All" class="btn btn-infos pull-right" style="visibility: hidden; margin-left: 5px;" id = "save_all_user" />
    <input type="button" value="Assign User" class="btn btn-inverse pull-right" id = "assign_user" style="visibility: hidden;"/>
    <div class="clearfix"></div>
    <div style="visibility: hidden;" id = "contributor-recipients" >
      <div style="float: left; margin-left: 30px;" ><h3> Feedback Contributor</h3></div>
      <div style="float:left;margin-left: 280px;"><h3> Feedback Recipients</h3></div>
    </div>
    <div class="clearfix"></div>
    <div class="content hero_unit" id="assign_user_content"  style="visibility: hidden;">
    </div>
    </br>
    <div><%= link_to "Back", admin_users_path, :class => "btn", :style => "float:left; visibility: hidden;", :id => "back-btn" %></div>
    <div align="center" style="visibility: hidden;" id = "message1">(Please click "Assign User" to add new set of fields.)</div>

<% else %>
    <div align="center" class="hero_unit"><h2>Assign to User before 6PM from Monday to Friday</h2></div></br>
    <div><%= link_to "Back", admin_users_path, :class => "btn"%></div>
<% end %>

app/views/admin/users/from_feedback.html.erb
<!--<div class="pull-right">-->
  <!--<input type="text" data-behaviour='datepicker' id="datepicker" >-->
  <!--<%#= link_to "search", nil, :class => "btn btn-info", :style => "margin-top:-9px; margin-left:-4px;", :remote => true, :id => "given-search" , :rel => @user.id %>-->
<!--</div>-->
<div class="clearfix"></div>
<div id="given_feedback">
  <%= render :partial => "from_feedback", :locals => {:users => @users, :feedbacks => @feedbacks, :user => @user,  :begin_date => @begin_date, :end_date =>  @begin_date.end_of_week,:next_month_begin_date => @begin_date.next_week.next_month.beginning_of_month.beginning_of_week , :next_month_end_date => @begin_date.next_week.next_month.beginning_of_month.end_of_week} %>
</div>

app/views/admin/users/given_feedback_search.js.erb
$("#given_feedback").html("<%= escape_javascript(render :partial => "from_feedback", :locals => {:users => @users, :feedbacks => @feedbacks, :user => @user,  :begin_date => @begin_date, :end_date =>  @begin_date.end_of_week,:next_month_begin_date => @begin_date.next_week.next_month.beginning_of_month.beginning_of_week , :next_month_end_date => @begin_date.next_week.next_month.beginning_of_month.end_of_week}) %>");

app/views/admin/users/index.html.erb
<table class="table" id="user_table">
  <colgroup>
    <col class="span2">
    <col class="span3">
    <col class="span3">
    <col class="span3">
  </colgroup>
  <caption>
    <h2>Weboniser List</h2>
  </caption>
  <thead>
  <tr style = "background-color: #333; color: #fff;">
    <th style="border-right:1px solid  #84c225;">ID</th>
    <th style="border-right:1px solid  #84c225;">Name</th>
    <th style="border-right:1px solid  #84c225;">Email</th>
    <th style="border-right:1px solid  #84c225;"><div align="center">
      <%= link_to "Assign User", assign_user_admin_users_path, :class => "btn btn-infos" %>
    </div>
    </th>
  </tr>
  </thead>
  <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td style="width: 450px !important;">
          <div align="center">
          <%= link_to "Received",to_feedback_admin_user_path(user), :class => "btn btn-infos" %>
          <%= link_to "Given & Assigned",from_feedback_admin_user_path(user), :class => "btn btn-infos" %>
          <%= link_to "Delete", delete_user_admin_user_path(user), :method => "DELETE", :class => "btn btn-infos",  :confirm => "Are you sure you want to delete #{user.name}?" %>
          <%= link_to "Reset Passsword", reset_password_admin_user_path(user), :class => "btn btn-infos" %>
          </div>
        </td>
      </tr>
  <% end %>
</table>
<%= page_navigation_links @users %>

app/views/admin/users/received_feedback_search.js.erb
$("#received_feedback").html("<%= escape_javascript(render :partial => "to_feedback", :locals => {:users => @users, :feedbacks => @feedbacks, :user => @user,  :begin_date => @begin_date, :end_date =>  @begin_date.end_of_week,:next_month_begin_date => @begin_date.next_week.next_month.beginning_of_month.beginning_of_week , :next_month_end_date => @begin_date.next_week.next_month.beginning_of_month.end_of_week}) %>");
$('.main-table').oneSimpleTablePagination({rowsPerPage:3});

app/views/admin/users/to_feedback.html.erb
<!--<div class="pull-right">-->
  <!--<input type="text" data-behaviour='datepicker' id="datepicker" >-->
  <!--<%#= link_to "search", nil, :class => "btn btn-info", :style => "margin-top:-9px; margin-left:-4px;", :remote => true, :id => "received-search" , :rel => @user.id %>-->
<!--</div>-->
<div id="received_feedback">
  <%= render :partial => "to_feedback", :locals => {:users => @users, :feedbacks => @feedbacks, :user => @user,  :begin_date => @begin_date, :end_date =>  @begin_date.end_of_week,:next_month_begin_date => @begin_date.next_week.next_month.beginning_of_month.beginning_of_week , :next_month_end_date => @begin_date.next_week.next_month.beginning_of_month.end_of_week} %>
</div>