config/routes.rb
Feedback::Application.routes.draw do

  get "home/index"

  resources :users, :only => [] do
    get :new_password, :on => :member
    put :create_password, :on => :member
    put :update_feedback, :on => :member
    get :change_password, :on => :member
    put :update_password, :on => :member
    put :update_reset_password, :on => :member
    get :reset_password, :on => :member
    get :give_feedback, :on => :collection
    get :received_feedback, :on => :collection
    get :received_feedback_search, :on => :collection
    get :forgot_password, :on => :collection
    post :forgot_password_reset, :on => :collection
  end

  namespace :admin do
    resources :admins, :only => [:index] do
      get :add_user, :on => :collection
      post :create_user, :on => :collection
      get :assigned_feedback_list, :on => :collection
      get :assigned_feedback_search, :on => :collection
      get :reset_password, :on => :member
      put :update_password, :on => :member
    end
    resources :users, :only => [:index] do
      get :assign_user, :on => :collection
      get :get_from_user_list, :on => :collection
      get :get_to_user_list, :on => :collection
      get :create_assign_user, :on => :collection
      get :given_feedback_search, :on => :collection
      get :received_feedback_search, :on => :collection
      get :to_feedback, :on => :member
      get :from_feedback, :on => :member
      delete :delete_user, :on => :member
      get :reset_password, :on => :member
    end
  end
  resources :user_sessions, :only => [:new, :create, :destroy]
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

  root :to => 'home#index'

end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController

  def new
    @user_session = UserSession.new
  end

  #NOTE create user session
  def create
    @user_session = UserSession.new(params[:user_session])
    if @user_session.save
      user = User.find_by_email(@user_session.email)
      if user.role == "admin"
        redirect_to admin_users_path, :notice => "Successfully logged in."
      else
        redirect_to give_feedback_users_path, :notice => "Successfully logged in."
      end
    else
      render :new
    end
  end

  #NOTE Destroy user session
  def destroy
    @user_session = UserSession.find(params[:id])
    @user_session.destroy
    redirect_to root_url, :notice => "Successfully logged out."
  end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/new.html.erb
<% if @user_session.errors.any? %>
    <div class="alert alert-error" align="center">
      <a class="close" data-dismiss="alert"> × </a>
      <% @user_session.errors.full_messages.each do |msg| %>
          <p><%= msg %></p>
      <% end %>
    </div>
<%end%>
<div class="row">
  <div class="span5 offset3 login_container" >
    <%= form_for @user_session, :html => { :class => "form-horizontal"} do |f| %>
        <legend>Login</legend>
        <div class="control-group">
          <label class="control-label">
            <%=f.label :email %>
          </label>
          <div class="controls">
            <%= f.email_field :email, :placeholder => "Email"%>
          </div>
        </div>
        <div class="control-group">
          <label class="control-label">
            <%=f.label :password %>
          </label>
          <div class="controls">
            <%= f.password_field :password %>
          </div>
        </div>
        <div class="control-group">
          <div class="controls">
            <%= f.submit "Log In", :class => "btn btn-inverse" %>
            <%= link_to "cancel", root_path, :class => "btn" %>
            <u ><%= link_to "Forgot your password?", forgot_password_users_path, :style =>"color: #84c225 !important;"%></u>
          </div>
        </div>
    <% end %>

  </div>
</div>
<div class="row">
  <div class="span10 offset2 webonise_logo">
    <img src="/assets/weboniselab.png" >
  </div>
</div>